dataset:
  type: euroc
  root_path: "/home/anupam/datasets/EuRoC/MH_01_easy"

playback:
  rate: 1.0
  loop: false

sensors:
  cam0:
    enabled: true

  cam1:
    enabled: true

  imu0:
    enabled: true